### ISSUE TITLE
Duolingo Desktop on Flathub

### ISSUE THREAD

**Issue by CharDSonDev** [hmlendea/dl-desktop#37]
I'd like to see this app on Flathub, I see you have another project in Flathub, so I guess you wouldn't have a hard time packaging Duolingo Desktop in Flatpak and publishing it on Flathub.

**Comment by hmlendea** [comment]
I also want Duolingo on Flathub too.

I will try to post it there when I can find the time for it. But in the meantime, if anyone else wants to do it sooner, that would be appreciated.

**Comment by hmlendea** [comment]
https://github.com/flathub/flathub/pull/2926

Soon™️

**Comment by CharDSonDev** [comment]
https://flathub.org/apps/details/ro.go.hmlendea.DL-Desktop

Already!
