### ISSUE TITLE
[Flathub Version] Javascript Error on App startup (the app works fine after pressing OK)

### ISSUE THREAD

**Issue by onfire4hire** [hmlendea/dl-desktop#54]
![image](https://user-images.githubusercontent.com/72320316/162575285-14ea08ce-6cb8-4e3f-a651-3b4580536807.png)

**Comment by hmlendea** [comment]
What version of the app are you using? What's the installation method?

**Comment by hmlendea** [comment]
Hi. Thanks for the report!

It was a packaging error. The next version should work well - coming soon!
