### ISSUE TITLE
[Flathub Version] Javascript Error on App startup (the app works fine after pressing OK) bug

### ISSUE THREAD

**Issue by onfire4hire** [hmlendea/dl-desktop#60]
The problem persists even after updating to the most recent version, tried purging and reinstalling the package.
![image](https://user-images.githubusercontent.com/72320316/162677080-2e38fa2b-f02f-43f4-969b-a424f6735113.png)

**Comment by hmlendea** [comment]
Reappearance of #54 

I've identified the issue and it will be fixed in the next version.

**Comment by onfire4hire** [comment]
No problem, thanks for your efforts!
