### ISSUE TITLE
 end-of-life org.freedesktop.Platform.GL.default branch 21.08

### ISSUE THREAD

**Issue by chrisfxwolf** [hmlendea/dl-desktop#80]
It's looks like is a time to update for branch 23.08. Is still working with old one but message was occurs:

> Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   ro.go.hmlendea.DL-Desktop

**Comment by DongshengHuang** [comment]
Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   ro.go.hmlendea.DL-Desktop

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   ro.go.hmlendea.DL-Desktop

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   ro.go.hmlendea.DL-Desktop
